### ISSUE TITLE
Multiple optionals doesn't work

### ISSUE THREAD

**Issue by pheyvaer** [rubensworks/GraphQL-LD.js#13]
Multiple optionals does not work with the following:

Context:
```
{
  "address": {"@id": "http://example.org/address"},
  "street": {"@id": "http://example.org/street"},
  "firstname": {"@id": "http://example.org/firstname"},
  "lastname": {"@id": "http://example.org/lastname"}
}
```

Query:
```
{  
  firstname @optional
  lastname @optional
  address {
    street
  }
}
```

Tested with both no data and data, but doesn't make a difference.
Results in this error
```
(node:8541) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
(node:8541) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of undefined
    at NestedLoopJoin.close (/Users/pieter/Developer/bug-graphql-ld/node_modules/asyncjoin/join/NestedLoopJoin.js:21:20)
    at NestedLoopJoin.set [as source] (/Users/pieter/Developer/bug-graphql-ld/node_modules/asynciterator/asynciterator.js:990:12)
    at NestedLoopJoin.TransformIterator (/Users/pieter/Developer/bug-graphql-ld/node_modules/asynciterator/asynciterator.js:969:27)
    at new MultiTransformIterator (/Users/pieter/Developer/bug-graphql-ld/node_modules/asynciterator/asynciterator.js:1383:21)
    at new NestedLoopJoin (/Users/pieter/Developer/bug-graphql-ld/node_modules/asyncjoin/join/NestedLoopJoin.js:11:9)
    at ActorRdfJoinNestedLoop.getOutput (/Users/pieter/Developer/bug-graphql-ld/node_modules/@comunica/actor-rdf-join-nestedloop/lib/ActorRdfJoinNestedLoop.js:13:22)
    at ActorRdfJoinNestedLoop.run (/Users/pieter/Developer/bug-graphql-ld/node_modules/@comunica/bus-rdf-join/lib/ActorRdfJoin.js:111:29)
    at ActorRdfJoinNestedLoop.runObservable (/Users/pieter/Developer/bug-graphql-ld/node_modules/@comunica/core/lib/Actor.js:57:29)
    at MediatorRace.mediate (/Users/pieter/Developer/bug-graphql-ld/node_modules/@comunica/core/lib/Mediator.js:80:22)
(node:8541) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 52)
(node:8541) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Expected result:
```
[ ]
```
The code to execute the query is reused from the README and the data is hosted via the latest version of `ldf-server`.

**Comment by rubensworks** [comment]
That looks like a deep error, either in asyncjoin or comunica.

**Comment by rubensworks** [comment]
Will be fixed in the next Comunica release https://github.com/comunica/comunica/pull/632
