### ISSUE TITLE
TypeError: source.destroy is not a function when executing query

### ISSUE THREAD

**Issue by pheyvaer** [rubensworks/GraphQL-LD.js#4]
When executing this query

```
{ 
  label
  start
  end
}
```
with this context
```
{
  "label":  { "@id": "http://www.w3.org/2000/01/rdf-schema#label" },
  "start":  { "@id": "http://schema.org/startDate" },
  "end":    { "@id": "http://schema.org/endDate" }
}
```
on this Turtle file hosted via a TPF server
```
@prefix : <http://example.com/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

:test a :Test;
  <http://schema.org/endDate> "2019-07-01";
  <http://schema.org/name> "test";
  <http://schema.org/startDate> "2019-06-27";
  rdfs:label "test" .
```
I get the following error
```
/Users/pieter/Developer/dhb-kg/node_modules/asynciterator-promiseproxy/node_modules/asynciterator/asynciterator.js:1089
      source.destroy();
             ^

TypeError: source.destroy is not a function
    at PromiseProxyIterator.TransformIterator._end (/Users/pieter/Developer/dhb-kg/node_modules/asynciterator-promiseproxy/node_modules/asynciterator/asynciterator.js:1089:14)
    at Immediate.end (/Users/pieter/Developer/dhb-kg/node_modules/asynciterator-promiseproxy/node_modules/asynciterator/asynciterator.js:263:36)
    at processImmediate (timers.js:634:17)

```

The following query _does_ work
```
{ 
  label
  start
}
```
I used the code in the README at "With a client-side query engine".

**Comment by rubensworks** [comment]
Any chance this TPF server is public somewhere?

Also, this *may* be the same problem as https://github.com/comunica/comunica/issues/292.

**Comment by pheyvaer** [comment]
No, I run the latest version of `ldf-server` with this `config.json`:
```
{
  "title": "My Linked Data Fragments server",

  "datasources": {
    "output": {
      "title": "output",
      "type": "TurtleDatasource",
      "description": "test",
      "settings": { "file": "output.ttl" }
    }
  },

  "prefixes": {
    "rdf":         "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs":        "http://www.w3.org/2000/01/rdf-schema#",
    "xsd":         "http://www.w3.org/2001/XMLSchema#",
    "dc":          "http://purl.org/dc/terms/",
    "foaf":        "http://xmlns.com/foaf/0.1/",
    "dbpedia":     "http://dbpedia.org/resource/",
    "dbpedia-owl": "http://dbpedia.org/ontology/",
    "dbpprop":     "http://dbpedia.org/property/",
    "hydra":       "http://www.w3.org/ns/hydra/core#",
    "void":        "http://rdfs.org/ns/void#"
  }
}
```

Regarding the other issue, if it's npm-related is there something that I can do when I install the package?

**Comment by rubensworks** [comment]
I would say, avoid npm and use yarn for now, as it seems to be ignoring semver ranges.

**Comment by pheyvaer** [comment]
Just tried with yarn and that works. Thanks for the suggestion.

**Comment by rubensworks** [comment]
Great!
I may want to report this (or fix it myself) at npm though, as this should not be able to go wrong like this.

**Comment by pheyvaer** [comment]
Yeah true. If it really is related to semver then it's quite a big issue, because I really would expect that such things are taken care across different setups and packages.
